all:
	gfortran  -O -static 2potsim_noskin.f                 -o ../bin/2potsim_noskin
	gfortran  -O -static 2potsim_skin.f                   -o ../bin/2potsim_skin
	gfortran  -O -static 2potsim_skin_parts.f             -o ../bin/2potsim_skin_parts
	gfortran  -O -static 2potsim_skin_spheres.f           -o ../bin/2potsim_skin_spheres
	gfortran  -O -static 2potsim_skin_spheresNN.f         -o ../bin/2potsim_skin_spheresNN
	gfortran  -O -static ccenter.f                        -o ../bin/ccenter
	gfortran  -O -static grid_asc2bin.f                   -o ../bin/grid_asc2bin
	cp              mat2phyl.pl                         ../bin/mat2phyl.pl
	gfortran  -O -static mkapbsin-apbs-ot-0.3.2.f         -o ../bin/mkapbsin-apbs-ot-0.3.2
	gfortran  -O -static mkapbsin.f                       -o ../bin/mkapbsin
	gfortran  -O -static mkdismx.f                        -o ../bin/mkdismx
	gfortran  -O -static mkgridin.f                       -o ../bin/mkgridin
	gfortran  -O -static mkkin.f                          -o ../bin/mkkin
	gfortran  -O -static mkuhbdin.f                       -o ../bin/mkuhbdin
	gfortran  -O -static modeller2grin.f                  -o ../bin/modeller2grin
	gfortran  -O -static n1potsim.f                       -o ../bin/n1potsim
	gfortran  -O -static nm1potsim.f                      -o ../bin/nm1potsim
	gfortran  -O -static npotsim.f                        -o ../bin/npotsim
	gfortran  -O -static qdipsim.f                        -o ../bin/qdipsim
	gfortran  -O -static smNextopred.f                    -o ../bin/smNextopred
	gfortran  -O -static uhbd_asc2bin.f                   -o ../bin/uhbd_asc2bin
	gfortran  -O -static whatif2uhbd.f                    -o ../bin/whatif2uhbd
	gfortran  -O -static 2potsim_skin_spheresU.f   -o ../bin/2potsim_skin_spheresU
