c PIPSA version 3.0 (Jan 2007)
      parameter(im_max=350,im3_max=15625000,npoimx=15625000)
c grid maximal dimension (im_max), im_max**3 and maximal no of points of "skin" 
c used in 2potsim*, grid_asc2bin, uhbd_asc2bin
      parameter (nprmx=999,nprmx2=498501)
c maximal no of proteins (nprmx) and nprmx*(nprmx-1)/2
c used in mkapbsin, mkdismx, mkkin, mkuhbdin, n1potsim, npotsim, qdipsim
c parameter (nprmx=3333,nprmx2=5552778)
c larger version
      parameter (namx=99999)
c maximal no of atoms per protein
c used in ccenter.f
