c converts uhbd output generated by command
c print apar mol 1 end
c to pqr file
      character*80 s
      character*4 aname,rname
c
c     1 n    ntrm     1   16.712   -7.578    3.996   -0.300    1.625
c123456789-123456789-123456789-123456789-123456789-123456789-123456789-
c (i6,1x,a4,1x,a4,1x,i5,5f9.3)  ia,aname,rname,ir,x,y,z,q,r
cATOM   8280  N   NTE   544     -13.336   3.045  35.885  0.185 1.824
c123456789-123456789-123456789-123456789-123456789-123456789-123456789-
c ('ATOM',i7,1x,a4,1x,a4,i5,4x,5f8.3 / f7.3,g6.3) ia,aname,rname,ir,x,y,z,q,r
c
 1    continue
      read(5,'(a)',end=51) s
      if(s(1:20).ne.'     Atom    Residue') goto 1
c
 2    continue
      read(5,'(a)',end=51) s
      if(s(1:20).eq.' Center of Geometry ') goto 51
      read(s,501) ia,aname,rname,ir,x,y,z,q,r
      write(6,502) ia,aname,rname,ir,x,y,z,q,r
      goto 2
 51   continue
 501  format(i6,1x,a4,1x,a4,1x,i5,5f9.3)
 502  format('ATOM',i7,1x,a4,1x,a4,i5,4x,3f8.3,f7.3,f6.3)
c
      call exit
      end
